"""add token

Revision ID: 5b1526949b64
Revises: b1fbc2280b9f
Create Date: 2023-09-09 01:20:45.211713

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "5b1526949b64"
down_revision = "b1fbc2280b9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("token", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.drop_column("token")

    # ### end Alembic commands ###
