"""add note

Revision ID: 8d93f91e9697
Revises: 5b1526949b64
Create Date: 2023-09-26 01:58:28.121469

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8d93f91e9697"
down_revision = "5b1526949b64"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.add_column(sa.Column("note", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.drop_column("note")

    # ### end Alembic commands ###
