"""init

Revision ID: b1fbc2280b9f
Revises:
Create Date: 2023-09-09 01:11:09.504599

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "b1fbc2280b9f"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "skland_subscribe",
        sa.Column("uid", sa.String(), nullable=False),
        sa.Column(
            "user", sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), "postgresql"), nullable=False
        ),
        sa.Column("cred", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("uid"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("skland_subscribe")
    # ### end Alembic commands ###
