"""remove_unique_note

Revision ID: b488a7927868
Revises: f9eda5d9d24e
Create Date: 2023-12-17 11:14:36.273477

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "b488a7927868"
down_revision = "f9eda5d9d24e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.drop_constraint("uq_skland_subscribe_note", type_="unique")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.create_unique_constraint("uq_skland_subscribe_note", ["note"])

    # ### end Alembic commands ###
