"""unique note

Revision ID: d89239244530
Revises: 8d93f91e9697
Create Date: 2023-09-26 03:10:07.153565

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "d89239244530"
down_revision = "8d93f91e9697"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f("uq_skland_subscribe_note"), ["note"])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("skland_subscribe", schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f("uq_skland_subscribe_note"), type_="unique")

    # ### end Alembic commands ###
